#!/bin/zsh -f

# .zshrc
#
# Useful references:
#   - http://zsh.sourceforge.net/Contrib/startup/std/zshrc

umask 077 # Permissions default to user only

# # Use hard limits, except for a smaller stack and no core dumps
# unlimit
# limit stack 8192
# limit core 0
# limit -s

# !! see: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
if [ "$(command -v "brew")" ] ; then
  # !! in case of warnings "zsh compinit: insecure directories", run:
  #
  #   $ chmod -R go-w "$(brew --prefix)/share/zsh"

  BREW_PREFIX='/usr/local'
  BREW_SHARE="$BREW_PREFIX/share"

  # !! Only makes sense if `zsh-completions` is installed via Homebrew
  [[ -d "$BREW_SHARE/zsh-completions" ]] &&
    fpath=( "$BREW_SHARE/zsh-completions" "$fpath[@]" )

  fpath=( "$BREW_SHARE/zsh/site-functions" "$fpath[@]" )
fi

if command -v fzf &>/dev/null; then
  # Auto-completion
  [[ $- == *i* ]] &&
    source "/usr/local/opt/fzf/shell/completion.zsh" 2> /dev/null

  # Key bindings
  source "/usr/local/opt/fzf/shell/key-bindings.zsh"
fi

# autoload -Uz compinit
# compinit

# Place .zcompdump and .zcompcache in XDG_CACHE_HOME

() {
  emulate -L zsh
  local -r cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/zsh
  autoload -Uz _store_cache compinit
  zstyle ':completion:*' use-cache true
  zstyle ':completion:*' cache-path $cache_dir/.zcompcache
  [[ -f $cache_dir/.zcompcache/.make-cache-dir ]] || _store_cache .make-cache-dir
  compinit -C -d $cache_dir/.zcompdump
}

if [[ $TERM =~ 'kitty' ]]; then
  # !! goes after compinit
  kitty + complete setup zsh | source /dev/stdin
  alias ssh="TERM='xterm-256color' ssh"
fi

typeset -U path cdpath fpath manpath

setopt hist_save_no_dups    # Do not write a duplicate event to the history file.
setopt auto_pushd           # Push the current directory visited on the stack.
setopt pushd_ignore_dups    # Do not store duplicates in the stack.
setopt pushd_silent         # Do not print the directory stack after pushd or popd.

unsetopt hist_verify

bindkey -e                 # emacs key bindings
bindkey ' ' magic-space    # also do history expansion on space
bindkey '^I' complete-word # complete on tab, leave expansion to _expand

# Aliases

alias vi="nvim"
alias ls="ls -Ghk"

alias e="$EDITOR"
alias l="exa --group-directories-first"

LSCOLORS='exfxcxdxbxegedabagacad'

# Zsh plugins installed via Homebrew

foreach plugin_name (
  "$BREW_SHARE/zsh-autosuggestions/zsh-autosuggestions.zsh"          \
  "$BREW_SHARE/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"  \
  "$BREW_SHARE/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh" \
  "$BREW_SHARE/zsh-history-substring-search/zsh-history-substring-search.zsh"
)
  [ -f $plugin_name ] &&
    source "$plugin_name"
end

export GHCUP_USE_XDG_DIRS=yes
source "$XDG_DATA_HOME/ghcup/env"

[ -f "/Users/p/.local/share/ghcup/env" ] && source "/Users/p/.local/share/ghcup/env" # ghcup-env

export PATH="/usr/local/opt/texinfo/bin:$PATH" # [2021-02-16]
export PATH="/usr/local/opt/bison/bin:$PATH"   # [2021-02-16]

command -v zoxide &>/dev/null && eval "$(zoxide init zsh)" # [2021-02-18]

export NVM_DIR="$HOME/.config/nvm" # [2021-03-_4]
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # [2021-03-_4] This loads nvm
