#!/bin/zsh -f

# .zshenv
#
# assumptions:
#  - ZDOTDIR is set
#  - Base Directory Specification is set

export EDITOR="nvim"
export VISUAL=$EDITOR

export PAGER="less"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export HISTFILE="${XDG_DATA_HOME-=$HOME/.local/share}/zsh/zsh_history"
export HISTSIZE=10000 # Maximum events for internal history
export SAVEHIST=10000 # Maximum events in history file

[ -d "$XDG_DATA_HOME/man" ] && mkdir -p "$XDG_DATA_HOME/man"

export MANPATH="$XDG_DATA_HOME/man:$MANPATH"
export PATH="/usr/local/lib/ruby/gems/3.0.0/bin:$HOME/.cargo/bin:$XDG_CONFIG_HOME/emacs/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:$PATH"
