#!/bin/zsh -f

# zshenv: always sourced, should contain exported variables
#         that should be available to other programs.
#         zshenv is sourced second, after /etc/zshenv

# Set up XDG Base Directory Specification
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

foreach dir ( $XDG_DATA_HOME $XDG_CONFIG_HOME $XDG_CACHE_HOME )
  [ -d $dir ] && mkdir -p $dir
end

[ -z ${ZDOTDIR+'no_zdotdir'} ] && export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

[ -r "$ZDOTDIR/.zshenv" ] && source "$ZDOTDIR/.zshenv"
